spring:
  application:
    name: 'cache'
  profiles:
    active: local

---

spring:
  profiles: local

  cache:
    type: redis

  redis:
    host: "localhost"
    port: 6379

  data:
    cassandra:
      contact-points: "localhost"
      keyspace-name: example
      port: 9042

server:
  port: 8080

# Management endpoints actuator
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - metrics
          - info
  metrics:
    enable:
      jvm.memory.used: true
      process.uptime: true
      jdbc.connections.active: true
      process.cpu.usage: true
      all: false
